/**
 * Shell-completion script emitters.
 *
 * Produces bash / zsh / pwsh completion scripts that plug into the user's
 * shell. The generated scripts cover two levels:
 *
 *   1. Top-level subcommand names (`claude-crusts <TAB>` → analyze, list, ...)
 *   2. Session-id prefix completion for the dozen commands whose first
 *      positional is `[session-id]` (e.g. `claude-crusts analyze 9b2<TAB>`)
 *
 * The scripts call back into the binary via `claude-crusts completion ids`,
 * which prints one session id per line. That internal subcommand is part of
 * the same surface area emitted here so users install one script and don't
 * need jq, awk, or PowerShell JSON parsing.
 *
 * Install examples (these live in the generated scripts' header comments):
 *
 *   bash:  claude-crusts completion bash >> ~/.bashrc
 *   zsh:   claude-crusts completion zsh  >> ~/.zshrc
 *   pwsh:  claude-crusts completion pwsh | Out-String | Invoke-Expression
 *
 * Design choice: subcommand lists are hard-coded rather than derived from
 * Commander at generation time. Rationale: keeps completion deterministic
 * across harness snapshots, makes the scripts testable without spinning up
 * the full CLI, and the list changes on the same cadence as index.ts
 * command additions — which is the right pair to keep in sync anyway.
 */

/** Top-level subcommands available at `claude-crusts <TAB>`. */
export const SUBCOMMANDS: readonly string[] = [
  'analyze', 'list', 'timeline', 'waste', 'fix', 'optimize',
  'compare', 'lost', 'watch', 'report', 'calibrate', 'trend',
  'tui', 'status', 'hooks', 'statusline', 'diff', 'models',
  'doctor', 'bench', 'completion',
];

/** Subcommands whose first positional is a session id (complete from `list`). */
export const SESSION_ID_SUBCOMMANDS: readonly string[] = [
  'analyze', 'timeline', 'waste', 'fix', 'optimize',
  'lost', 'watch', 'report', 'tui', 'status', 'diff', 'models',
];

/** Shells we emit a completion script for. */
export type CompletionShell = 'bash' | 'zsh' | 'pwsh';

/**
 * Emit a bash completion script.
 *
 * Install:
 *   claude-crusts completion bash >> ~/.bashrc     # persist across shells
 *   source ~/.bashrc                                # or open a new shell
 */
export function generateBashCompletion(): string {
  const commands = SUBCOMMANDS.join(' ');
  const sessionCmds = SESSION_ID_SUBCOMMANDS.join(' ');
  return `# bash completion for claude-crusts
# Generated by \`claude-crusts completion bash\` — safe to append to ~/.bashrc.
_claude_crusts_completion() {
  local cur cword words
  cur="\${COMP_WORDS[COMP_CWORD]}"
  cword=\$COMP_CWORD
  words=("\${COMP_WORDS[@]}")

  local commands="${commands}"
  local session_cmds=" ${sessionCmds} "

  if [ "\$cword" -eq 1 ]; then
    COMPREPLY=( \$(compgen -W "\$commands" -- "\$cur") )
    return
  fi

  local cmd="\${words[1]}"
  if [ "\$cword" -eq 2 ] && [[ "\$session_cmds" == *" \$cmd "* ]]; then
    local ids
    ids=\$(claude-crusts completion ids 2>/dev/null)
    COMPREPLY=( \$(compgen -W "\$ids" -- "\$cur") )
    return
  fi
}
complete -F _claude_crusts_completion claude-crusts
`;
}

/**
 * Emit a zsh completion script.
 *
 * Install:
 *   claude-crusts completion zsh >> ~/.zshrc
 *   source ~/.zshrc
 *
 * Use `_describe` rather than `compadd` so `menuselect` and fuzzy matchers
 * work as users expect.
 */
export function generateZshCompletion(): string {
  const commandsList = SUBCOMMANDS.map((c) => `'${c}'`).join(' ');
  const sessionCmdsList = SESSION_ID_SUBCOMMANDS.map((c) => `'${c}'`).join(' ');
  return `#compdef claude-crusts
# zsh completion for claude-crusts
# Generated by \`claude-crusts completion zsh\` — safe to append to ~/.zshrc.

_claude_crusts() {
  local -a commands session_cmds
  commands=(${commandsList})
  session_cmds=(${sessionCmdsList})

  if (( CURRENT == 2 )); then
    _describe 'subcommand' commands
    return
  fi

  local cmd=\${words[2]}
  if (( CURRENT == 3 )) && [[ \${session_cmds[(r)\$cmd]} == \$cmd ]]; then
    local -a ids
    ids=(\${(f)"\$(claude-crusts completion ids 2>/dev/null)"})
    _describe 'session-id' ids
  fi
}
_claude_crusts "\$@"
`;
}

/**
 * Emit a PowerShell completion script.
 *
 * Install:
 *   claude-crusts completion pwsh | Out-String | Invoke-Expression
 *
 * Or persist by appending to \$PROFILE.
 */
export function generatePowerShellCompletion(): string {
  const commands = SUBCOMMANDS.map((c) => `'${c}'`).join(', ');
  const sessionCmds = SESSION_ID_SUBCOMMANDS.map((c) => `'${c}'`).join(', ');
  return `# PowerShell completion for claude-crusts
# Generated by \`claude-crusts completion pwsh\`. Append to $PROFILE to persist.
Register-ArgumentCompleter -Native -CommandName claude-crusts -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)
  $tokens = $commandAst.CommandElements
  $tokenCount = $tokens.Count

  $commands = @(${commands})
  $sessionCmds = @(${sessionCmds})

  # Subcommand position (first token is the binary itself)
  if ($tokenCount -le 2) {
    $commands | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
      [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
    }
    return
  }

  # Session-id position: ask the binary for the id list
  $cmdName = $tokens[1].Value
  if ($tokenCount -eq 3 -and $sessionCmds -contains $cmdName) {
    $ids = & claude-crusts completion ids 2>$null
    $ids | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
      [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
    }
  }
}
`;
}

/** Dispatch table for `claude-crusts completion <shell>`. */
export function generateCompletionScript(shell: CompletionShell): string {
  switch (shell) {
    case 'bash': return generateBashCompletion();
    case 'zsh': return generateZshCompletion();
    case 'pwsh': return generatePowerShellCompletion();
  }
}
